export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_GENRE = 'UPDATE_GENRE';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const EXPORT_COLOR = 'EXPORT_COLOR';
export const FETCH_COLOR_BEGIN = 'FETCH_COLOR_BEGIN';
export const FETCH_COLOR_SUCCESS = 'FETCH_COLOR_SUCCESS';
export const FETCH_COLOR_FAILURE = 'FETCH_COLOR_FAILURE';
export const ADD_TEXT = 'ADD_TEXT';